[package]
name = "runtime-desktop"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "rt_desktop"

[dependencies]
runtime-core = { path = "../core" }
runtime-pe = { path = "../pe" }
png = "0.18"
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
